# Generated by Django 4.0 on 2022-08-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_basicinfo_image_roominfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='app.room'),
        ),
    ]
