# Generated by Django 4.1 on 2022-08-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='brokerAgency',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tag',
        ),
        migrations.AlterField(
            model_name='room',
            name='options',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.option'),
        ),
    ]
