# Generated by Django 4.0 on 2022-08-10 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_interest_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeragency',
            name='brokerAgency_company_registration_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='brokeragency',
            name='brokerAgency_number1',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')]),
        ),
        migrations.AlterField(
            model_name='brokeragency',
            name='brokerAgency_number2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')]),
        ),
        migrations.AlterField(
            model_name='brokeragency',
            name='brokerAgency_registration_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='basicInfo_brokerAgency_contact',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')]),
        ),
    ]
