# Generated by Django 4.1 on 2022-08-07 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_room_brokeragency_remove_room_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tag'),
        ),
    ]
