# Generated by Django 4.1 on 2022-08-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_room_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tag',
        ),
        migrations.AddField(
            model_name='room',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
    ]
