# Generated by Django 4.0.6 on 2022-08-06 19:00

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_basicinfo_basicinfo_move_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=app.utils.rename_imagefile_to_uuid),
        ),
    ]
