# Generated by Django 4.0.6 on 2022-08-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_roominfo_remove_confirmedroom_checklist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='tag',
            new_name='tags',
        ),
    ]
