# Generated by Django 4.0.6 on 2022-08-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_tag_room_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='tags',
            new_name='tag',
        ),
    ]
