# Generated by Django 4.0.6 on 2022-08-08 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_rename_tags_room_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='is_confirmed',
        ),
        migrations.CreateModel(
            name='ConfirmedRoom',
            fields=[
                ('confirmedRoom_id', models.AutoField(primary_key=True, serialize=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.checklist')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.room')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
