# Generated by Django 4.0.6 on 2022-08-09 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_checklist_is_confirmed_confirmedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='app.room'),
        ),
    ]
