# Generated by Django 4.0 on 2022-08-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='basicInfo_move_in_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
